from fastapi.security import OAuth2PasswordBearer

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGRmMjIzZjFkMWM4NmIwMjRiNDM4MiIsIm5hbWUiOiJzdHJpbmciLCJlbWFpbCI6InRlc3RpbmdAdGVzdC5jb20iLCJyb2xlIjoidXNlciIsImV4cCI6MTczODIzMzUxOH0.Ky60KFlGBBrlkyA2quv0S3QJjAys8yfdmC_NlJJKL9w")

